using System;
using System.Collections.Generic;
using ManiaPlanetSharp.GameBox.Parsing.Chunks;

namespace ManiaPlanetSharp.GameBox.Parsing.ParserGeneration.AutoGenerated
{
	public static partial class AutoGeneratedParsers
	{
		public static Dictionary<Type, IParser<object>> StructParsers { get; } = new Dictionary<Type, IParser<object>> {
			{ typeof(ManiaPlanetSharp.GameBox.Parsing.Chunks.Checkpoint), new CheckpointParser() },
			{ typeof(ManiaPlanetSharp.GameBox.Parsing.Chunks.Block), new BlockParser() },
			{ typeof(ManiaPlanetSharp.GameBox.Parsing.Chunks.VisualModelStruct1), new VisualModelStruct1Parser() },
			{ typeof(ManiaPlanetSharp.GameBox.Parsing.Chunks.VisualModelStruct2), new VisualModelStruct2Parser() },
			{ typeof(ManiaPlanetSharp.GameBox.Parsing.Chunks.VisualModelStruct3), new VisualModelStruct3Parser() },
			{ typeof(ManiaPlanetSharp.GameBox.Parsing.Chunks.VisualModelStruct4), new VisualModelStruct4Parser() },
